apiVersion: v1
kind: Service
metadata:
  name: my-country-service
spec:
  type: NodePort
  selector:
    app: my-country-service
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 31000